### PR TITLE
Adding nodeSelector option for PodSpec

### PR DESCRIPTION
**Pull request by aignatov**

### CODE REVIEW

**Comment by shamil** [comment]
@aignatov not sure this is needed, there is already `Affinity` in the spec that can do that

**Comment by aignatov** [comment]
> @aignatov not sure this is needed, there is already `Affinity` in the spec that can do that

@shamil thanks for your reply. My use case is as follows:
- My redis pods has to be scheduled only to specific nodes with specific labels
- I also use anitiAffininty option not to collocate two pods with similar labels

Unfortunately I didn't find better way how to organize such deployment w/o nodeSelector option.

**Comment by shamil** [comment]
I've similar requirement, this is what I put in `Affinity` block

```
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: dedicated
            operator: In
            values:
            - redis
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app.kubernetes.io/instance: tokens
            app.kubernetes.io/name: redis
        topologyKey: kubernetes.io/hostname
```

**Comment by aignatov** [comment]
@shamil you're right, it's possible to do so but I'm worried about performance of old k8s clusters with several hundreds of nodes. Here is a opened discussion about it:
https://github.com/kubernetes/kubernetes/issues/72479

Also _nodeSelector_ looks like straightforward option (just like clear node filtering by labels) for other cases which may not requiring complex affinity rules. I mean why not have this option if k8s allows it. :)

**Comment by toha10** [comment]
LGTM

**Comment by toha10** [comment]
@nrvnrvn or somebody with permissions on merge, please take a look

**Comment by nrvnrvn** [comment]
@aignatov thanks for the contribution
@toha10 thanks for the heads up ;)

**Pull request merged**
