### PR TITLE
Bump operator-sdk version to v1.13.0

### LINKED ISSUE #40: Bump operator-sdk version to v1.11.0
Use latest version of operator-sdk

### PR DESCRIPTION
**Pull request by AKamyshnikova**
Refactor structure for migration to v1.x from
v0.19.4.

https://v0-19-x.sdk.operatorframework.io/docs/golang/project_migration_guide/

Fixes: #40

Signed-off-by: akamyshnikova <akamyshnikova@mirantis.com>

Change-Id: If4f7f77f7ff42938a08b105c706b6fe660bb72b7

### CODE REVIEW

**Comment by nrvnrvn** [comment]
@AKamyshnikova thank you so much for opening up this PR, this is a really huge effort!

Give me some time to review it.

**Comment by AKamyshnikova** [comment]
@nrvnrvn Hi! I've updated commit with refresh of some broken dependencies.

**Comment by shamil** [comment]
@nrvnrvn is this something is planned to be merged?

**Comment by nrvnrvn** [comment]
@AKamyshnikova @shamil 

Hey guys!

I finally have some time to address some long standing tickets and PRs and make some changes.

Let me review this change and test it and revert back to you until Monday.

**Comment by nrvnrvn** [comment]
I have reviewed the current state of the code, this pull request and given that I have a limited access to the project I decided to continue development in a fork and start off with using the latest stable kubebuilder and finally address all the bullet points mentioned in https://github.com/nrvnrvn/redis-operator/issues/1

Please follow https://github.com/nrvnrvn/redis-operator. There is a lot to come in the coming days and weeks.

**Comment by AKamyshnikova** [comment]
@nrvnrvn Should I repropose commit to https://github.com/nrvnrvn/redis-operator ? Switch to kubebuilder was part of currect PR https://github.com/amaizfinance/redis-operator/pull/41/commits/fbcae231efa18a38f661bb424e46f85c0d7577a9#diff-d1fb402f1269ba7396dca9cbd03b44ac055874669bce1d0f239fa2f54ea3584b

**Pull request closed without merging**
