### PR TITLE
Bump operator-sdk to 0.17.1 version

### PR DESCRIPTION
**Pull request by toha10**
- code changes to support operator-sdk 0.17.1 version
- updated dependencies

### CODE REVIEW

**Comment by toha10** [comment]
@nrvnrvn could you please take a look ? thanks

**Comment by nrvnrvn** [comment]
Hi @toha10 ,

it makes sense to leave the `vendor` dir because bazel which is currently used as a build system for the project cannot automatically resolve all the dependency requirements:

```
$ ./hack/build/test.sh 
+ bazel test --features=race //...
Starting local Bazel server and connecting to it...
ERROR: /redis-operator/cmd/manager/BUILD.bazel:3:11: no such package 'vendor/github.com/operator-framework/operator-sdk/version': BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - /redis-operator/vendor/github.com/operator-framework/operator-sdk/version and referenced by '//cmd/manager:go_default_library'
ERROR: Analysis of target '//cmd/manager:manager_image.binary' failed; build aborted: Analysis failed
INFO: Elapsed time: 30.745s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (27 packages loaded, 211 targets configured)
FAILED: Build did NOT complete successfully (27 packages loaded, 211 targets configured)
    currently loading: @io_bazel_rules_go//go/platform
```

I suggest to run `./hack/update-deps.sh` which will sync and cleanup all deps and re-generate `BUILD.bazel` files for each module.

**Comment by toha10** [comment]
@nrvnrvn thanks for review, i've updated my PR according to your comment

**Comment by nrvnrvn** [comment]
Thanks a lot for that @toha10

**Pull request merged**
