### PR TITLE
Bump operator-sdk version

### LINKED ISSUE #35: Bump operator-sdk version
Project development requires usage higher version of operator-sdk and kubernetes.

Update operator-sdk to 0.19.x and go to 1.16, unlocking following updates.

### PR DESCRIPTION
**Pull request by AKamyshnikova**
Update operator-sdk to 0.19.4 and related k8s.io modules
to v0.19.13.

Bump go version to 1.16

Fixes #35

Signed-off-by: akamyshnikova <akamyshnikova@mirantis.com>

### CODE REVIEW

**Comment by AKamyshnikova** [comment]
@nrvnrvn Could you please take a look at this bump?

**Comment by nrvnrvn** [comment]
hi @AKamyshnikova,

Thank you for raising this PR.

Please apply the following diff to the WORKSPACE file:
```diff
diff --git a/WORKSPACE b/WORKSPACE
index f27423e6..3ba18f7d 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -34,9 +34,9 @@ gazelle_dependencies()
 # fetch and load rules_docker
 http_archive(
     name = "io_bazel_rules_docker",
-    sha256 = "95d39fd84ff4474babaf190450ee034d958202043e366b9fc38f438c9e6c3334",
-    strip_prefix = "rules_docker-0.16.0",
-    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.16.0/rules_docker-v0.16.0.tar.gz"],
+    sha256 = "59d5b42ac315e7eadffa944e86e90c2990110a1c8075f1cd145f487e999d22b3",
+    strip_prefix = "rules_docker-0.17.0",
+    urls = ["https://github.com/bazelbuild/rules_docker/releases/download/v0.17.0/rules_docker-v0.17.0.tar.gz"],
 )
 
 load(
```

Run the `./hack/update-deps.sh` script and then run the tests `./hack/build/test.sh`

**Comment by AKamyshnikova** [comment]
@nrvnrvn Done

**Comment by nrvnrvn** [comment]
thank you so much!

**Pull request merged**
